name: Email Notifications Cron Job

on:
  schedule:
    # Chạy mỗi ngày lúc 9:00 AM UTC (16:00 VN)
    - cron: '0 9 * * *'
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Start application
        run: |
          npm run build
          npm start &
          sleep 30
          
      - name: Run cron job
        run: |
          curl -X GET http://localhost:3001/api/cron/notifications
          
      - name: Check results
        run: |
          echo "Cron job completed successfully"