name: Email Notifications Cron Job

on:
  schedule:
    # Chạy mỗi 5 phút
    - cron: '*/5 * * * *'
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      - name: Start application in background
        run: |
          npm start &
          sleep 10
          
      - name: Run cron job
        run: |
          curl -X GET http://localhost:3000/api/cron/notifications
          
      - name: Stop application
        run: |
          pkill -f "npm start" || true
          pkill -f "next start" || true
          
      - name: Check results
        run: |
          echo "Cron job completed successfully"
